config/routes.rb
StripeRailsExample::Application.routes.draw do

  root 'accounts#new'

  get 'accounts/new' => 'accounts#new'
  get 'accounts' => 'accounts#index'
  post 'accounts' => 'accounts#create'

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  protect_from_forgery with: :exception

  def index
    Stripe.api_key = "sk_test_f6xQ9zdAdLxmNWbv1fC3CIxq"
    @accounts = Stripe::Customer.all
  end

  def create
    Stripe.api_key = "sk_test_f6xQ9zdAdLxmNWbv1fC3CIxq"

    # Create a Customer
    customer = Stripe::Customer.create(
      card: params[:stripe_token],
      plan: "monthly",
      email: params[:email],
      metadata: {
        first_name: params[:first_name],
        last_name: params[:last_name]
      }
    )

    account = Account.new
    account.stripe_customer_id = customer.id
    success = account.save

    if success
      flash[:notice] = "Customer registered!"
      redirect_to accounts_path
    else
      flash[:success] = "Could not sign up user!"
      redirect_to accounts_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/index.html.erb
<div class="accounts">
  <h1>Accounts</h1>

  <% @accounts.each do |account| %>
    <%= account.email %><br>
  <% end %>

  <%= link_to "Create New Account", accounts_new_path %>
</div>

app/views/accounts/new.html.erb
<div class="accounts-signup">
  <h1>Join the Tie of the Month Club!</h1>

  <p>Life isn't the same without new ties. Now there's an easy way to stay up-to-date with current trends and look suave in the process!</p>

  <%= form_for :account, url: { action: "create" }, html: { id: "stripe-form" } do %>
    <span class="payment-errors"></span>

    <label>Name</label>
    <input name="first_name" placeholder="First Name">
    <input name="last_name" placeholder="Last Name">

    <label>Email</label>
    <input type="email" name="email" placeholder="myname@company.com">

    <label>Card Number</label>
    <input size="20" data-stripe="number" placeholder='xxxx-xxxx-xxxx-xxxx'>

    <label>CVC</label>
    <input size="4" data-stripe="cvc" placeholder='xxx'>

    <label>Expiration (MM/YYYY)</label>
    <input size="2" data-stripe="exp-month" placeholder="MM">
    <input size="4" data-stripe="exp-year" placeholder="YYYY">

    <button type="submit">Subscribe!</button>
  <% end %>
</div>

<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
  Stripe.setPublishableKey('pk_test_uIJsrtuEg4PIP4OffdwRRB1P');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tie of the Month Club</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>